# SPDX-FileCopyrightText: 2021-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later OR GPL-2.0-only

name: "Assemble"

on:
    pull_request:
        branches: [ master, stable-* ]

# Declare default permissions as read only.
permissions: read-all

concurrency:
    group: assemble-flavors-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    flavor:
        runs-on: ${{ matrix.runner }}
        strategy:
            fail-fast: false
            matrix:
                flavor: [ Generic, Gplay, Huawei ]
                runner: [ ubuntu-latest, blaze/ubuntu-22.04-amd64 ]
        steps:
            -   uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
            -   name: set up JDK 17
                uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
                with:
                    distribution: "temurin"
                    java-version: 17
            -   name: Build ${{ matrix.flavor }}
                run: |
                    echo "org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" >> gradle.properties
                    ./gradlew assemble${{ matrix.flavor }}
